#!/bin/bash

# mount -t proc proc /proc
# mount -t sysfs sys /sys
# mount -t devtmpfs devtmpfs /dev

echo "====================================================="
echo
echo "Ramix Init"
echo
echo "====================================================="

while true; do
    /bin/bash
    echo
    echo "Shell exited. Restarting..."
    echo
    sleep 1
done