name = "curl"
version = "8.21.0"
release = 1

arch = "x86_64"

license = "curl"

description = "Command line tool and library for transferring data with URLs"

homepage = "https://curl.se/"

maintainer = "Ramix Team"

depends = [
    "glibc>=2.43",
    "openssl>=3.5.2",
    "zlib>=1.3.2",
    "ca-certificates>=20250630"
]