name = "readline"
version = "8.3"
release = 1

arch = "x86_64"

license = "GPL-3.0-or-later"

description = "GNU Readline library"

homepage = "https://tiswww.case.edu/php/chet/readline/rltop.html"

maintainer = "Ramix Team"

depends = [
    "glibc>=2.43",
    "ncurses>=6.6"
]